const JWT_SECRET_KEY = "RtdqqLnNN15qym8rJAd40ka7MBG4GX9a";
const JWT_SECRET_ADMIN_KEY = "oUsyzvvsmtmt3Yf7FVzD5ft2vNH3zF9N";
const JWT_SUPERADMIN_SECRET_KEY ="yHkwQeXwBVqJOlVqg5mnZDn9hOq1STtQ";
const JWT_MANAGERADMIN_SECRET_KEY="ptCiyN6SsgdHTyS6TOU5hueUuNGLiZGm";
const JWT_CUSTOMER_SECRET_KEY = "APY5qZ1MAPOf3lOyKYUek50mqj0oy1Su";

module.exports = {
    JWT_SECRET_KEY,
    JWT_SECRET_ADMIN_KEY,
    JWT_SUPERADMIN_SECRET_KEY,
    JWT_MANAGERADMIN_SECRET_KEY,
    JWT_CUSTOMER_SECRET_KEY
}